{% set name = "cubo" %}
{% set version = "2026.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cubo/cubo-{{ version }}.tar.gz
  sha256: 11813daa18418b0cac26ad431770ea5aa98d0b28ce62aec0a82ff45276c47675

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=68
    - wheel
    - pip
  run:
    - python >=3.10
    - dask-core >=2023.7.0
    - numpy
    - pandas >=2.0.3
    - planetary-computer >=1.0.0
    - pystac-client >=0.7.2
    - scipy >=1.12.0
    - stackstac >=0.5.1
    - xarray >=2023.6.0

test:
  imports:
    - cubo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ESDS-Leipzig/cubo
  summary: On-Demand Earth System Data Cubes in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://cubo.readthedocs.io/en/latest/
  dev_url: https://github.com/ESDS-Leipzig/cubo

extra:
  recipe-maintainers:
    - davemlz
